#!/bin/sh

dir=~/dotfiles                    # dotfiles directory
olddir=~/.dotfiles_old             # old dotfiles backup directory

logAndRun() {
    local cmd=$*
    echo $cmd
    $cmd
    if [[ $? != 0 ]]
    then
        echo "ERROR: command failed"
        echo "please rectify and re-run"
        exit 1
    fi
}

move_if_exists() {
    local file=$1
    local dir=$2
    if [[ -e $file ]]
    then
        logAndRun mv $file $dir
    fi
}


rename_if_exists() {
    local file=$1
    if [[ -e $file ]]
    then
        logAndRun mv $file ${file}.bak
    fi
}

logAndRun mkdir -p $olddir
logAndRun cd $dir

while read file
do
    if [[ ! -L ~/$file ]]   # if not already a link
    then
        rename_if_exists $olddir/$file
        move_if_exists  mv ~/$file $olddir
        #logAndRun mv ~/$file $olddir
        logAndRun ln -sf $dir/$file ~/$file
    else
        echo "$file ok"
    fi
done < $dir/dotfiles_list

echo "installing new .gitconfig"
# .gitconfig is special, need to edit it with original user/email
if [[ -f ~/.gitconfig ]]
then
  git_name=`git config --global --get user.name`
  git_email=`git config --global --get user.email`
  cp .gitconfig $olddir
  cp .gitconfig ~
  git config --global user.name $git_name
  git config --global user.email $git_email
  if [[ -z $git_name || -z $git_email ]]
  then
    echo "Warning: git user or email looks blank."
    echo "Check ~/.gitconfig"
  fi
fi
