#!/bin/sh

dir=~/dotfiles                    # dotfiles directory
olddir=~/.dotfiles_old             # old dotfiles backup directory

logAndRun() {
    cmd=$*
    echo $cmd
    $cmd
}

logAndRun mkdir -p $olddir
logAndRun cd $dir

while read file
do
    if [[ ! -L $file ]]
    then
        logAndRun mv ~/$file $olddir
        logAndRun ln -s $dir/$file ~/$file
    else
        echo "$file is already a link"
    fi
done < $dir/dotfiles_list

if [[ -f ~/.gitconfig ]]
then
  git_name=`git config --global --get user.name`
  git_email=`git config --global --get user.email`
  cp .gitconfig $olddir
  cp .gitconfig ~
  git config --global user.name $git_name
  git config --global user.email $git_email
  if [[ -z $git_name || -z $git_email ]]
  then
    echo "Warning: git user or email looks blank."
    echo "Check ~/.gitconfig"
  fi
fi
